apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000  # Modifié pour correspondre au port exposé dans le Dockerfile
  selector:
    app: fastapi-app