name: Build and Push Image

on:
  push:
    branches: 
      - main  # Déclenche le workflow sur les poussées vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Assurez-vous que cette ligne correspond à la version recommandée ou plus récente
      - uses: actions/checkout@v3  # Mise à jour à la dernière version
      - name: Build Docker image
        run: |
          docker build -t username/myapp:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push username/myapp:${{ github.sha }}