name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.0  # Mise à jour vers une version plus récente

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.5.0  # Mise à jour vers une version plus récente
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Install GKE gcloud auth plugin
      run: |
        echo "${{ secrets.GCLOUD_AUTH }}" | base64 --decode > gcloud.json
        curl https://sdk.cloud.google.com | bash
        echo "source /home/runner/google-cloud-sdk/path.bash.inc" >> $GITHUB_ENV
        source /home/runner/google-cloud-sdk/path.bash.inc
        gcloud auth activate-service-account --key-file=gcloud.json
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/myapp-deployment