name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0  # Utilisation d'une version spécifique

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.0  # Utilisation d'une version spécifique pour l'action auth
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Install GKE gcloud auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/myapp-deployment