name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
    - name: Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/myapp-deployment