name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ${HOME}/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/myapp-deployment